//Run these commands in you npm console 
// run on local machine change file location where you json is located-> 
// for windows: export GOOGLE_APPLICATION_CREDENTIALS="C:\Users\Mansoor\Desktop\CalHacks2022\calgaryhack2022-36518d7424ea.json"
// for mac: export GOOGLE_APPLICATION_CREDENTIALS="C:\Users\Mansoor\Desktop\CalHacks2022\calgaryhack2022-36518d7424ea.json"
// npm install --save @google-cloud/firestore

//Initialize an instance of Firestore:
console.log('Hello world initializing firestore DB!');
const Firestore = require('@google-cloud/firestore');

const db = new Firestore({
    projectId: 'calgaryhack2022',
    keyFilename: '\calgaryhack2022-36518d7424ea.json',
});

console.log('Instantiated an instance of the DB!');
//========**testing**==========
console.log('Testing printing user data!');
print_users();
console.log('Done testing user data!');

var addr= get_user_addr('alovelace');
console.log(addr);
// console.log('Testing adding users');
// add_users('nuha', 'shaikh', 'she/her', 20, '614b 17 Ave SW, Calgary, AB T2S 0B4', 'nuha.shaikh1@ucalgary.ca', '403-455-9917', 'password1234');
// console.log('done testing adding users');

print_users();
//=======**end-testing**========

//=========================USER DB FUNCTIONALITIES=====================================
//Add a new user to the User collection
function add_users(first, last, pronouns, org_id, home_addr, email, phone_num, password){
    //autogenerated ID
    const data={
        first: first,
        last: last,
        pronouns: pronouns,
        org_id: org_id,
        home_addr: home_addr,
        email: email,
        phone_num:phone_num,
        password: password
    };
    (async function(){
        // Add a new document with a generated id.
        const res = await db.collection('users').add(data);
        console.log('Added document with ID: ', res.id);
    })()
}


function delete_user(user_id){ //pass the id of document -> id of specific user
    (async function(){
        const res = await db.collection('users').doc(user_id).delete();
    })()
}

//pass user_id
function get_user_addr(doc_id){
    const usersRef = db.collection('users');
    (async function(){
        const snapshot = await usersRef.get();
        return snapshot.home_addr;
    })()
}

function print_users(){
    //printing out each collection
    console.log("In print_users function!");
    (async function(){
        console.log("In print_users async function!");
        const snapshot = await db.collection('users').get();
        snapshot.forEach((doc) => {
        console.log(doc.id, '=>', doc.data());
    });
    })()
}
//=========================**END USER DB FUNCTIONALITIES**=====================================

// //Add a new organization to the organization collection
// function add_users(first, last, pronouns, org_id, home_addr, email, phone_num, password){
//     //autogenerated ID
//     (async function(){
//         // Add a new document with a generated id.
//         const res = await db.collection('users').add({
//         first: first,
//         last: last,
//         pronouns: pronouns,
//         org_id: org_id,
//         home_addr: home_addr,
//         email: email,
//         phone_num:phone_num,
//         password: password
//     });
// });
// }

// function delete_user(user_id){ //pass the id of document -> id of specific user
//     (async function(){
//         const res = await db.collection('users').doc(user_id).delete();
//     });
// }

// function print_user(){
//     //printing out each collection
//     (async function(){
//         const snapshot = await db.collection('users').get();
//     });
//     snapshot.forEach((doc) => {
//     console.log(doc.id, '=>', doc.data());
//     });
// }
//=========================ORG DB FUNCTIONALITIES=====================================


//=========================**ORG USER DB FUNCTIONALITIES**=====================================

//Create a new collection and a document using the following example code.


